# Generated by Django 5.0.2 on 2024-02-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_details',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=100)),
                ('passport_id', models.CharField(max_length=100)),
            ],
        ),
    ]
