# Generated by Django 5.0.2 on 2024-03-01 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_updatedcustomerdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdatedCustomerDetails',
        ),
    ]
