# Generated by Django 5.0.2 on 2024-03-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_delete_updatedcustomerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatedCustomerDetails',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=100)),
                ('passport_id', models.CharField(max_length=100)),
            ],
        ),
    ]
